[package]
name = "atlas-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
atlas-daemon-protocol.workspace = true
daemonkit = "0.1.0"
serde_json.workspace = true
thiserror.workspace = true
tokio = { version = "1", features = ["io-std", "io-util", "rt", "macros"] }
