use atlas_schema::{FactId, FactRow, FactWarrant, Provenance, SourceEvidence};

/// Conservative classification emitted before a legacy fact can be mapped into
/// a v3 claim/evidence graph. No classification is itself evidence.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum LegacyDisposition {
    FormalEvidencePendingReceipt,
    StructuralEvidenceCandidate,
    DocumentaryEvidenceCandidate,
    EmpiricalEvidenceCandidate,
    NumericalEvidenceCandidate,
    ResearchProposal,
    LegacyUnverifiedFormal,
    LegacyUnverifiedStructural,
    LegacyUnattributedAssertion,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LegacyImportDiagnostic {
    pub fact: FactId,
    pub disposition: LegacyDisposition,
    pub reason: String,
}

pub fn classify_legacy_fact(fact: &FactRow) -> LegacyImportDiagnostic {
    let (disposition, reason) = match &fact.provenance {
        Provenance::Oracle { receipt } => (
            LegacyDisposition::FormalEvidencePendingReceipt,
            format!(
                "oracle receipt {:?} must be resolved, environment-scoped and replayed before formal evidence is created",
                receipt
            ),
        ),
        Provenance::Source { source, evidence } => match evidence {
            SourceEvidence::Formal if fact.warrant == FactWarrant::Proved => (
                LegacyDisposition::LegacyUnverifiedFormal,
                format!(
                    "formal source {source:?} has no durable v3 proof receipt attached at the legacy boundary"
                ),
            ),
            SourceEvidence::Formal => (
                LegacyDisposition::FormalEvidencePendingReceipt,
                format!(
                    "formal source {source:?} was explicitly downgraded; retain that downgrade"
                ),
            ),
            SourceEvidence::Structural => (
                LegacyDisposition::StructuralEvidenceCandidate,
                format!(
                    "structural source {source:?} requires an explicit comparator or derivation record"
                ),
            ),
            SourceEvidence::Assertion => (
                LegacyDisposition::DocumentaryEvidenceCandidate,
                format!("source assertion {source:?} requires a source anchor"),
            ),
            SourceEvidence::Empirical => (
                LegacyDisposition::EmpiricalEvidenceCandidate,
                format!(
                    "empirical source {source:?} requires a dataset/observation receipt and scope"
                ),
            ),
            SourceEvidence::Numerical => (
                LegacyDisposition::NumericalEvidenceCandidate,
                format!(
                    "numerical source {source:?} requires executable, inputs, environment and run receipt"
                ),
            ),
            SourceEvidence::Heuristic => (
                LegacyDisposition::ResearchProposal,
                format!(
                    "heuristic source {source:?} is proposal/search metadata, not claim evidence"
                ),
            ),
            SourceEvidence::Unclassified => (
                LegacyDisposition::LegacyUnattributedAssertion,
                format!("source {source:?} has no classified evidence semantics"),
            ),
        },
        Provenance::Derived { .. } => {
            let derivations = fact.provenance.derivations();
            if derivations.is_empty() || derivations.iter().all(|path| path.inputs.is_empty()) {
                (
                    LegacyDisposition::LegacyUnverifiedStructural,
                    "derived provenance has no non-empty support path".into(),
                )
            } else {
                (
                    LegacyDisposition::StructuralEvidenceCandidate,
                    format!(
                        "retain {} alternative derivation path(s) as an OR-of-AND support circuit",
                        derivations.len()
                    ),
                )
            }
        }
        Provenance::Candidate { method, .. } => (
            LegacyDisposition::ResearchProposal,
            format!("candidate generated by {method:?} remains a proposal"),
        ),
    };

    LegacyImportDiagnostic {
        fact: fact.id,
        disposition,
        reason,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use atlas_schema::{FactId, RelationTypeId, Value};

    #[test]
    fn formal_source_is_not_promoted_without_a_receipt() {
        let fact = FactRow {
            id: FactId(1),
            relation: RelationTypeId(1),
            args: vec![],
            warrant: FactWarrant::Proved,
            provenance: Provenance::Source {
                source: "paper".into(),
                evidence: SourceEvidence::Formal,
            },
        };
        assert_eq!(
            classify_legacy_fact(&fact).disposition,
            LegacyDisposition::LegacyUnverifiedFormal
        );
    }

    #[test]
    fn empty_derived_provenance_is_downgraded() {
        let fact = FactRow {
            id: FactId(2),
            relation: RelationTypeId(1),
            args: vec![Value::Text("x".into())],
            warrant: FactWarrant::Structural,
            provenance: Provenance::derived("empty", vec![]),
        };
        assert_eq!(
            classify_legacy_fact(&fact).disposition,
            LegacyDisposition::LegacyUnverifiedStructural
        );
    }

    #[test]
    fn candidate_remains_a_proposal() {
        let fact = FactRow {
            id: FactId(3),
            relation: RelationTypeId(1),
            args: vec![],
            warrant: FactWarrant::Heuristic,
            provenance: Provenance::Candidate {
                method: "intuition".into(),
                evidence: vec![],
            },
        };
        assert_eq!(
            classify_legacy_fact(&fact).disposition,
            LegacyDisposition::ResearchProposal
        );
    }
}
