#!/usr/bin/env python3
"""Turn the REFUTED ledger into `#atlas_home_attempt` shards — the refuter lane's generator.

§42's census left 1,858 REFUTED verdicts, and REFUTED means only "this declaration's own
proof term does not survive the weakening" — the statement's truth is unknown, because
nothing in this project had ever tried to prove one (§65 verified that in source: no prover
appears anywhere in the loop). `#atlas_home_attempt` asks the other question: state the exact
weakening and hand it to a tactic ladder. A PROVED line is sound and final — a new theorem,
established by an argument the original declaration did not use. A `not proved` line means
only that this ladder did not find it within its budget.

Allocation follows `probe-plan.py`'s census convention: ordered **by family** (declared ->
target pair), largest family first, candidates sorted by name inside a family — so an
interrupted run still leaves whole families measured, and the run is reproducible with no
randomness. Shards are cut sequentially from that order.

**Every shard carries three planted controls**, and this is the load-bearing part. The
first attempt run in this repo probed the wrong binder for 55 cases before anyone noticed
(`kuna-math-loop.md` §1); a lane that will run unattended needs its control *in every
round*, not in a fixture that ran once. Each shard opens with the `AttemptSmoke.lean` trio
under collision-proof names, attempted with the same ladder as the data lines:

* `atlas_plant_easy`      — commutativity under `CommRing`, weakened to `AddCommMagma`.
                         Exactly an `AddCommMagma` fact: **must read PROVED**.
* `atlas_plant_hard`      — additive cancellation, same weakening. Well-formed but not an
                         `AddCommMagma` law: **must read `not proved`**.
* `atlas_plant_no_statement` — multiplicative commutativity, same weakening. `*` has no
                         instance there: **must read NO STATEMENT**.

`score-attempts.py` discards a shard whose plants come back wrong, unread. What a good
answer looks like, stated before the run: all plants correct in every shard, and — on the
precedent of the kuna replay-3 event, where the generic ladder did not rediscover the
expert's argument — a PROVED rate well under the 19.4% kernel-confirmation rate. Zero
PROVED across all 1,858 would itself be a real measurement: it would say these ladders add
nothing over re-elaboration, and the prover budget belongs elsewhere.
"""

from __future__ import annotations

import argparse
import collections
import json
import pathlib

DEFAULT_SCORED = [
    pathlib.Path("/tmp/atlas-gen-scored-v2.json"),
    pathlib.Path("/tmp/atlas-probeplan-scored.json"),
    pathlib.Path("/tmp/atlas-proberest-scored.json"),
]

# The two runners differ only here: `lake env lean` needs the file to import its own
# environment, `atlas_batch` supplies the environment and refuses a file that names one.
IMPORTS = """import Mathlib
import Atlas.Home

"""

HEADER = """/-
Copyright (c) 2026 The lean-atlas contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
{imports}/-!
# Attempt shard {shard} of {total_shards} — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#atlas_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `atlas_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`Atlas.Home`, not `Atlas` — importing the language puts the file's top
level into Atlas's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats {heartbeats}
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem atlas_plant_easy {{R : Type}} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem atlas_plant_hard {{R : Type}} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem atlas_plant_no_statement {{R : Type}} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#atlas_home_attempt atlas_plant_easy CommRing => AddCommMagma by {plant_ladder}
#atlas_home_attempt atlas_plant_hard CommRing => AddCommMagma by {plant_ladder}
#atlas_home_attempt atlas_plant_no_statement CommRing => AddCommMagma by {plant_ladder}
"""


def load_refuted(paths: list[pathlib.Path]) -> list[tuple[str, str, str]]:
    """Every REFUTED (decl, declared, target), deduplicated, first occurrence kept."""
    seen: set[tuple[str, str, str]] = set()
    out: list[tuple[str, str, str]] = []
    for p in paths:
        for decl, declared, target in json.loads(p.read_text())["refuted"]:
            k = (decl, declared, target)
            if k not in seen:
                seen.add(k)
                out.append(k)
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--scored", type=pathlib.Path, nargs="+", default=DEFAULT_SCORED,
                    help="scored probe runs whose `refuted` lists form the population")
    ap.add_argument("--from-attempts", type=pathlib.Path, default=None,
                    help="take the population from a scored *attempt* run instead — "
                         "e.g. round 2 re-asks round 1's not_proved with a deeper ladder")
    ap.add_argument("--key", default="not_proved",
                    help="which list to take from --from-attempts")
    ap.add_argument("--triples", type=pathlib.Path, default=None,
                    help="take the population from a plain triples file "
                         '({"triples": [[decl, source, target], ...]}) — e.g. '
                         "recovery-triples.py's statable-level candidates")
    ap.add_argument("--exclude", type=pathlib.Path, nargs="*", default=[],
                    help="scored attempt runs whose triples to skip (already asked)")
    ap.add_argument("--budget", type=int, default=0,
                    help="cap on attempts; 0 means the whole population (a census)")
    ap.add_argument("--shard-size", type=int, default=80,
                    help="attempts per emitted file; each shard pays one Mathlib import, "
                         "so bigger amortises better and smaller reports sooner")
    ap.add_argument("--ladder", default="rfl, simp, aesop, exact?",
                    help="tactic ladder, cheapest first; named here because Home.lean "
                         "imports only core Lean and cannot name Mathlib tactics itself")
    ap.add_argument("--plant-ladder", default=None,
                    help="ladder for the planted controls, when the data ladder's plant "
                         "verdicts are not known in advance. The plants validate the "
                         "machinery (rebuild, resynthesis, timeout conversion, verdict "
                         "emission); their required verdicts are facts about the round-1 "
                         "ladder, so a new data ladder keeps the plants on the known one.")
    ap.add_argument("--heartbeats", type=int, default=1000000,
                    help="per-command budget; timeouts convert to bounded misses, so this "
                         "is the time price of a miss, not a correctness knob")
    ap.add_argument("--out-dir", type=pathlib.Path, default=pathlib.Path("lean/Scratch"))
    ap.add_argument("--prefix", default="AttemptPlan")
    ap.add_argument("--index", type=pathlib.Path,
                    default=pathlib.Path("/tmp/atlas-attempt-plan.json"))
    ap.add_argument("--batch", action="store_true",
                    help="emit headerless shards for `atlas_batch`, which imports Mathlib "
                         "once per worker instead of once per shard")
    args = ap.parse_args()

    if args.triples:
        raw = [tuple(t) for t in json.loads(args.triples.read_text())["triples"]]
        seen_t: set[tuple[str, str, str]] = set()
        population = [t for t in raw if not (t in seen_t or seen_t.add(t))]
        print(f"{len(population):,} triples from {args.triples}")
    elif args.from_attempts:
        rows = json.loads(args.from_attempts.read_text())[args.key]
        seen: set[tuple[str, str, str]] = set()
        population = []
        for r in rows:
            k = (r["decl"], r["source"], r["target"])
            if k not in seen:
                seen.add(k)
                population.append(k)
        print(f"{len(population):,} triples from {args.from_attempts} [{args.key}]")
    else:
        population = load_refuted(args.scored)
        print(f"{len(population):,} REFUTED triples across {len(args.scored)} scored run(s)")

    done: set[tuple[str, str, str]] = set()
    for p in args.exclude:
        sc = json.loads(p.read_text())
        for k in ("proved", "not_proved", "no_statement"):
            for row in sc.get(k, []):
                done.add((row["decl"], row["source"], row["target"]))
    if done:
        before = len(population)
        population = [t for t in population if t not in done]
        print(f"  excluding {before - len(population):,} already attempted")

    # probe-plan.py's census ordering: whole families first, deterministic throughout.
    by_fam: dict[tuple[str, str], list] = collections.defaultdict(list)
    for decl, declared, target in population:
        by_fam[(declared, target)].append((decl, declared, target))
    fams = sorted(by_fam, key=lambda f: (-len(by_fam[f]), f))
    for f in fams:
        by_fam[f].sort()
    chosen = [t for f in fams for t in by_fam[f]]
    if args.budget:
        chosen = chosen[: args.budget]

    shards = [chosen[i : i + args.shard_size]
              for i in range(0, len(chosen), args.shard_size)]
    args.out_dir.mkdir(parents=True, exist_ok=True)
    index_shards = []
    for i, shard in enumerate(shards, 1):
        name = f"{args.prefix}{i:02d}"
        path = args.out_dir / f"{name}.lean"
        lines = [f"#atlas_home_attempt {decl} {declared} => {target} by {args.ladder}"
                 for decl, declared, target in shard]
        path.write_text(
            HEADER.format(shard=i, total_shards=len(shards), ladder=args.ladder,
                          plant_ladder=args.plant_ladder or args.ladder,
                          heartbeats=args.heartbeats,
                          imports="" if args.batch else IMPORTS)
            + "\n" + "\n".join(lines) + "\n")
        index_shards.append(
            {"file": str(path), "name": name,
             "probes": [{"decl": d, "source": s, "target": t} for d, s, t in shard]})

    fam_chosen = collections.Counter((s, t) for _d, s, t in chosen)
    args.index.write_text(json.dumps(
        {"ladder": args.ladder, "total": len(chosen),
         "families": len(fam_chosen), "shards": index_shards}, indent=1))
    print(f"\n{len(chosen):,} attempts over {len(fam_chosen):,} families "
          f"-> {len(shards)} shard(s) of <= {args.shard_size} in {args.out_dir}/")
    print(f"index -> {args.index}")
    print("\nrun each shard from lean/ with its own exit status captured, e.g.:")
    print("  (lake env lean Scratch/AttemptPlan01.lean) > /tmp/atlas-attempt-AttemptPlan01.log"
          " 2>&1; echo EXIT=$? >> /tmp/atlas-attempt-AttemptPlan01.log")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
