#!/usr/bin/env python3
"""The generalization pipeline, end to end, on whatever slice you point it at.

Produces candidate hypothesis weakenings, checks each against the corpus for an existing
general version, and emits a Lean file that puts the survivors in front of the kernel.

## What each stage is for

1. **Candidates** — `atlas_home`'s citation evidence rule: the classes a declaration's cited
   constants require, walked down the typeclass lattice. Restricted to declarations whose
   instance binders all constrain one carrier, where the flat evidence set and the
   carrier-aware one coincide by construction.
2. **Novelty screen, two ways.** `equivalent` at `instances` level catches a general version
   stated identically; a near-duplicate sweep at retention >= 0.85 with strictly weaker
   binders catches one stated differently. A candidate that fails either is rediscovery, not
   generation, and is reported separately rather than dropped — the ratio is the interesting
   number.
3. **Kernel probes** — `#atlas_home_refute <decl> <class>` forces the proposed weakening and
   reports the kernel's verdict. `CONFIRMED` is sound and final; `REFUTED` is inconclusive
   (instance projections were baked in at first elaboration), so the confirmation rate is a
   **lower bound** on precision and says nothing about recall.

## Why the shipped linters do not already do this

`unusedArguments` fires only when a binder is used *nowhere*. This fires when a binder is
genuinely used but only through operations a weaker class supplies. `Additive.ofMul_le`'s
`Preorder` binder really is used, for the `<=` in its statement; its proof needs only `LE`.
Mathlib's `unusedDecidableInType` is off by default, `Decidable`-only, and asks about the
type rather than the proof.
"""

from __future__ import annotations

import argparse
import collections
import json
import pathlib
import sys
import time

sys.path.insert(0, str(pathlib.Path(__file__).parent))
import atlas_home  # noqa: E402

try:
    import atlas as fa
except ImportError:
    sys.exit("atlas is not importable — run under `uv run`")

HEADER = """/-
Copyright (c) 2026 The lean-atlas contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import Atlas.Home

/-!
# Candidate generalizations — kernel probes

Generated by `scripts/generalization-run.py`. Each line forces a proposed hypothesis
weakening and reports the kernel's verdict: `CONFIRMED` means the declaration's own proof
term typechecks with the weaker class, which is sound and final. `REFUTED` is inconclusive.

`Atlas.Home`, not `Atlas` — importing the language puts the file's top
level into Atlas's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--slice", type=pathlib.Path, required=True)
    ap.add_argument("--out", type=pathlib.Path,
                    default=pathlib.Path("lean/Scratch/GeneralizationsFull.lean"))
    ap.add_argument("--index", type=pathlib.Path,
                    default=pathlib.Path("/tmp/atlas-gen-index.json"))
    ap.add_argument("--max-probes", type=int, default=600)
    ap.add_argument("--skip-novelty", action="store_true",
                    help="emit probes for every candidate, screening afterwards")
    args = ap.parse_args()

    t0 = time.time()
    rows = {}
    with args.slice.open() as fh:
        for line in fh:
            if line.strip():
                r = json.loads(line)
                rows[r["name"]] = r
    print(f"{len(rows):,} rows in {time.time() - t0:.0f}s")

    idx = atlas_home.HomeIndex(rows)
    print(f"lattice: {len(idx.classes):,} classes, "
          f"{sum(len(v) for v in idx.parents.values()):,} edges; "
          f"{len(idx.forgetful):,} forgetful instances ({time.time() - t0:.0f}s)")

    stat: collections.Counter = collections.Counter()
    cands: list[tuple[str, str, str]] = []
    for n, r in rows.items():
        if r.get("kind") != "theorem":
            continue
        v = idx.home(n)
        if v is None:
            stat["no-instance-binder"] += 1
            continue
        if "skipped" in v:
            stat[v["skipped"]] += 1
            continue
        stat["judged"] += 1
        if v["projection_like"]:
            stat["projection-like"] += 1
            continue
        for b in v["binders"]:
            if b["verdict"] == "over-hypothesis" and b.get("home"):
                cands.append((n, b["class"], b["home"]))
                stat["over-hypothesis"] += 1
            elif b["verdict"] == "unused":
                stat["unused (no target to force)"] += 1
    print(f"\ncandidate generation ({time.time() - t0:.0f}s):")
    for k, v in stat.most_common():
        print(f"  {k:32s} {v:8,}")
    print(f"  {'CANDIDATES with a target':32s} {len(cands):8,}")

    # ---- novelty screen ---------------------------------------------------------------
    novel, rediscovery = cands, []
    if not args.skip_novelty:
        c = fa.Corpus.load(str(args.slice))
        print(f"\nnovelty screen over {len(cands):,} candidates "
              f"({time.time() - t0:.0f}s)…")
        novel, rediscovery = [], []
        for i, (n, cls, home) in enumerate(cands):
            if i and i % 2000 == 0:
                print(f"  ..{i:,}/{len(cands):,} ({time.time() - t0:.0f}s)")
            try:
                if c.equivalent(n, level="instances"):
                    rediscovery.append((n, cls, home, "equivalent"))
                    continue
            except Exception:
                pass
            novel.append((n, cls, home))
        print(f"  rediscovery (general version already stated): {len(rediscovery):,}")
        print(f"  novel candidates                            : {len(novel):,}")

    probes = novel[:args.max_probes]
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        HEADER + "\n" + "\n".join(f"#atlas_home_refute {n} {home}" for n, _c, home in probes)
        + "\n")
    args.index.write_text(json.dumps(
        {"candidates": len(cands), "novel": len(novel),
         "rediscovery": len(rediscovery), "stat": dict(stat),
         "probes": [{"decl": n, "declared": c_, "target": h} for n, c_, h in probes]},
        indent=1))
    print(f"\n{len(probes):,} probes -> {args.out}")
    print(f"index -> {args.index}   ({time.time() - t0:.0f}s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
