#!/usr/bin/env python3
"""Emit a Lean file that puts each candidate weakening in front of the kernel.

## What this measures, and what it cannot

`#atlas_home_refute <decl> <class>` forces a weakening target and reports the kernel's answer.
Forcing matters: `#atlas_home_confirm` re-derives its own candidate from its own evidence, so
running it would score Lean's detector rather than the one under test. Forcing puts *this*
script's proposal in front of the kernel.

The two verdicts are not symmetric, and Home.lean is explicit about why:

* **CONFIRMED** — the declaration's own proof term typechecks with the weaker hypothesis.
  That is sound and final: the binder was an over-hypothesis, and the weakened statement is
  a theorem that now exists.
* **REFUTED** — inconclusive, not a disproof. The elaborator baked instance projections
  into the value when it was first checked, and retyping the binder can break that chain
  whether or not the proof needed the strength.

So this measures **precision** and can say nothing about recall. Any rate below is
"of the candidates proposed, how many were real", never "of the real ones, how many were
found".

## The strata, chosen before the run

The question is whether the crossing beats its halves, so the sample is stratified by which
detectors fired, and each stratum gets a forced target from whichever detector proposed one:

* `BOTH`  — both detectors flagged it; target from the citation detector.
* `L_ONLY` — only the citation detector; its proposed home.
* `S_ONLY` — only the shape detector; the weaker sibling's declared class.

A crossing that is worth the name confirms at a higher rate in `BOTH` than in either
single-detector stratum. If all three rates come out equal, the conjunction bought nothing
and the honest report says so.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import random

HEADER = """\
/-
Generated by `scripts/make-confirm-file.py` — do not edit by hand.

Each `#atlas_home_refute` forces one candidate weakening and asks the kernel. CONFIRMED means
the declaration's term typechecks with the weaker hypothesis; REFUTED is inconclusive (see
`Atlas/Atlas/Home.lean`). The `#guard_msgs`-free form is deliberate: this file is a
measurement, not a fixture, and pinning the verdicts would defeat its purpose.
-/
import Mathlib
import Atlas.Home

-- `Atlas.Home`, not `Atlas`: importing the language puts the file's
-- top level into Atlas's own command grammar, and the next `#`-command fails with
-- "unexpected token '#'; expected atlas_item". The tool is a Lean command and needs only the
-- module that defines it.

set_option maxHeartbeats 1000000
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--crossing", type=pathlib.Path,
                    default=pathlib.Path("/tmp/atlas-crossing-lattice-shape.json"))
    ap.add_argument("--out", type=pathlib.Path,
                    default=pathlib.Path("/home/dev/research/lean-atlas/lean/Scratch/HomeConfirm.lean"))
    ap.add_argument("--index", type=pathlib.Path,
                    default=pathlib.Path("/tmp/atlas-confirm-index.json"))
    ap.add_argument("--per-stratum", type=int, default=120)
    ap.add_argument("--seed", type=int, default=20260803)
    args = ap.parse_args()

    data = json.loads(args.crossing.read_text())
    rnd = random.Random(args.seed)

    def target_from_l(binders: list) -> str | None:
        for b in binders:
            if b.get("verdict") == "over-hypothesis" and b.get("home"):
                return b["home"]
        return None

    picks: list[tuple[str, str, str]] = []  # (stratum, decl, forced class)

    for name, both in data["agree"].items():
        t = target_from_l(both["L"])
        if t:
            picks.append(("BOTH", name, t))

    l_only = [(n, target_from_l(v)) for n, v in data["only_l"].items()]
    l_only = [(n, t) for n, t in l_only if t]
    rnd.shuffle(l_only)
    picks += [("L_ONLY", n, t) for n, t in l_only[:args.per_stratum]]

    s_only = []
    for n, v in data["only_s"].items():
        weaker = v.get("weaker") or []
        if not weaker:
            continue
        # The sibling's declared classes; force the first that is not already declared here.
        cand = [c for c in weaker[0]["declares"] if c not in v["declares"]]
        if cand:
            s_only.append((n, cand[0]))
    rnd.shuffle(s_only)
    picks += [("S_ONLY", n, t) for n, t in s_only[:args.per_stratum]]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    lines = [HEADER]
    for stratum, name, cls in picks:
        lines.append(f"-- {stratum}")
        lines.append(f"#atlas_home_refute {name} {cls}")
    args.out.write_text("\n".join(lines) + "\n")

    args.index.write_text(json.dumps(
        [{"stratum": s, "decl": n, "forced": c} for s, n, c in picks], indent=1))

    counts: dict[str, int] = {}
    for s, _n, _c in picks:
        counts[s] = counts.get(s, 0) + 1
    print(f"{len(picks)} probes → {args.out}")
    for s, k in sorted(counts.items()):
        print(f"  {s:8s} {k}")
    print(f"index → {args.index}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
