#!/usr/bin/env python3
"""Choose which candidates to put in front of the kernel, and why those.

§37 measured per-family confirmation rates and found them bimodal — families at 100% and
families at 0%, with the aggregate 32.4% a mixture rather than a property. That changes what
a probe is worth. A 79th probe into `Preorder -> LE` sharpens an estimate already built on
78; a first probe into a family with none tells you something no other probe can.

So allocation here is **by family, not by candidate**. Every askable family gets up to
`--per-family` probes before any family gets more, which maximises the number of families
with a usable rate rather than the number of probes.

Two exclusions, both measured rather than assumed:

* **Arity-changing weakenings** (§38). `weakenBinder` applies the target class to the source
  class's arguments, so `Zero R -> OfNat R` is under-applied and ill-typed. All 134 such
  probes in the previous run were "refuted" and none could have been anything else. The
  command now refuses them outright, so probing them spends budget to be told NO VERDICT.
  Counted and reported, never silently dropped.
* **Families already measured to `--saturated` probes.** Not excluded from the *result* —
  their rate is already known and applies to their candidates — only from the probe budget.

Nothing is filtered on a *prediction*. A family measured at 0% still gets its allocation on
this run, because `REFUTED` means "this proof term fails" and not "no proof exists", and
CLAUDE.md's rule is that narrowing needs its own control. The 0% families are where a
surprise would be most informative.
"""

from __future__ import annotations

import argparse
import collections
import json
import pathlib
import sys
import time

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from atlas_home import telescope  # noqa: E402

HEADER = """/-
Copyright (c) 2026 The lean-atlas contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import Atlas.Home

/-!
# Stratified kernel probes over the whole-Mathlib candidate set

Generated by `scripts/probe-plan.py`. Allocation is per weakening *family* rather than per
candidate, because §37 found confirmation rates bimodal and a family with no measured rate
is worth more than a 79th probe into one already measured on 78.

`Atlas.Home`, not `Atlas` — importing the language puts the file's top
level into Atlas's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
"""


def class_arity(path: str, t0: float) -> dict[str, int]:
    """How many arguments each class takes, as observed in instance-binder domains."""
    seen: dict[str, collections.Counter] = collections.defaultdict(collections.Counter)
    for i, line in enumerate(open(path)):
        if i % 200000 == 0:
            print(f"  [arity] {i:,}  {time.time() - t0:.0f}s", flush=True)
        if not line.strip():
            continue
        r = json.loads(line)
        s = r.get("stmt")
        if not s:
            continue
        try:
            b, _c = telescope(s)
        except Exception:
            continue
        for bi, h, args, _d in b:
            if bi == "t" and h:
                seen[h][len(args)] += 1
    return {c: k.most_common(1)[0][0] for c, k in seen.items()}


def emit(args, chosen, fam_chosen, prev, askable, unaskable) -> None:
    newly = sum(1 for f in fam_chosen if prev[f] == 0)
    print(f"  families with NO prior rate: {newly:,}")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        HEADER + "\n"
        + "\n".join(f"#atlas_home_refute {r['decl']} {r['target']}" for r in chosen) + "\n")
    args.index.write_text(json.dumps(
        {"probes": [{"decl": r["decl"], "declared": r["declared"], "target": r["target"]}
                    for r in chosen],
         "askable": len(askable), "unaskable": len(unaskable),
         "families_covered": len(fam_chosen), "families_new": newly}, indent=1))
    print(f"\n{len(chosen):,} probes -> {args.out}")
    print(f"index -> {args.index}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--candidates", type=pathlib.Path,
                    default=pathlib.Path("/tmp/atlas-gen-closure-candidates.json"))
    ap.add_argument("--slice", type=pathlib.Path,
                    default=pathlib.Path("/tmp/mathlib-closure.jsonl"))
    ap.add_argument("--scored", type=pathlib.Path,
                    default=pathlib.Path("/tmp/atlas-gen-scored-v2.json"),
                    help="previous run, to know which families are already measured")
    ap.add_argument("--budget", type=int, default=1200)
    ap.add_argument("--per-family", type=int, default=4)
    ap.add_argument("--saturated", type=int, default=12)
    ap.add_argument("--arity-slice", type=pathlib.Path, default=None,
                    help="where to read class arities from; defaults to --slice. A smaller "
                         "closure is fine and much faster — arity is a property of the "
                         "class, not of the corpus — and a class missing from it is left "
                         "askable, since the command refuses a mismatch at runtime anyway.")
    ap.add_argument("--exclude-probed", type=pathlib.Path, nargs="*", default=[],
                    help="scored runs whose (decl, declared, target) triples to skip")
    ap.add_argument("--all-remaining", action="store_true",
                    help="probe every remaining askable candidate rather than sampling "
                         "per family — turns a rate estimate into complete coverage")
    ap.add_argument("--out", type=pathlib.Path,
                    default=pathlib.Path("lean/Scratch/ProbePlan.lean"))
    ap.add_argument("--index", type=pathlib.Path,
                    default=pathlib.Path("/tmp/atlas-probe-plan.json"))
    args = ap.parse_args()
    t0 = time.time()

    rows = json.loads(args.candidates.read_text())["rows"]
    arity = class_arity(str(args.arity_slice or args.slice), t0)
    print(f"{len(rows):,} candidates; {len(arity):,} classes with an observed arity "
          f"({time.time() - t0:.0f}s)")

    done: set[tuple[str, str, str]] = set()
    for p in args.exclude_probed:
        sc = json.loads(pathlib.Path(p).read_text())
        for k in ("confirmed", "refuted", "inconclusive", "unaskable"):
            for decl, dc, tg in sc.get(k, []):
                done.add((decl, dc, tg))
    if done:
        before = len(rows)
        rows = [r for r in rows
                if (r["decl"], r["declared"], r["target"]) not in done]
        print(f"  excluding {before - len(rows):,} already-probed "
              f"({len(done):,} triples across {len(args.exclude_probed)} run(s))")

    askable, unaskable = [], []
    for r in rows:
        a, b = arity.get(r["declared"]), arity.get(r["target"])
        (unaskable if (a is not None and b is not None and a != b) else askable).append(r)
    print(f"  askable                    : {len(askable):,}")
    print(f"  arity-changing (unaskable) : {len(unaskable):,}  "
          f"(§38 — the command refuses these; probing them spends budget on NO VERDICT)")

    prev = collections.Counter()
    if args.scored.exists():
        sc = json.loads(args.scored.read_text())
        for k in ("confirmed", "refuted"):
            for _d, dc, tg in sc[k]:
                prev[(dc, tg)] += 1

    by_fam: dict[tuple[str, str], list] = collections.defaultdict(list)
    for r in askable:
        by_fam[(r["declared"], r["target"])].append(r)
    # Deterministic: sort candidates inside a family, and families by how little is known
    # about them, then by size. No randomness — the run must be reproducible.
    fams = sorted(by_fam, key=lambda f: (prev[f], -len(by_fam[f]), f))
    for f in fams:
        by_fam[f].sort(key=lambda r: r["decl"])

    if args.all_remaining:
        # Complete coverage rather than a sample. Ordered by family so the log reads as a
        # census, and so an interrupted run still leaves whole families measured.
        chosen = [r for f in fams for r in by_fam[f]][:args.budget]
        fam_chosen = collections.Counter((r["declared"], r["target"]) for r in chosen)
        print(f"\ncomplete-coverage plan ({time.time() - t0:.0f}s):")
        print(f"  probes                     : {len(chosen):,}")
        print(f"  families covered           : {len(fam_chosen):,}")
        left = sum(len(v) for v in by_fam.values()) - len(chosen)
        print(f"  askable candidates left over: {left:,}"
              + ("  <- raise --budget for full coverage" if left else "  <- none: every "
                 "askable candidate is probed"))
        emit(args, chosen, fam_chosen, prev, askable, unaskable)
        return 0

    chosen, round_no = [], 0
    while len(chosen) < args.budget and round_no < args.per_family:
        progressed = False
        for f in fams:
            if prev[f] >= args.saturated and round_no >= 1:
                continue          # already measured; one probe still guards against drift
            if len(by_fam[f]) > round_no and len(chosen) < args.budget:
                chosen.append(by_fam[f][round_no])
                progressed = True
        if not progressed:
            break
        round_no += 1

    fam_chosen = collections.Counter((r["declared"], r["target"]) for r in chosen)
    print(f"\nprobe plan ({time.time() - t0:.0f}s):")
    print(f"  probes                     : {len(chosen):,}")
    print(f"  families covered           : {len(fam_chosen):,} of {len(by_fam):,} askable")
    print(f"  median probes per family   : "
          f"{sorted(fam_chosen.values())[len(fam_chosen) // 2]}")

    emit(args, chosen, fam_chosen, prev, askable, unaskable)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
